### ISSUE TITLE
tm4c123

### ISSUE THREAD

**Issue by raako71** [fmilburn3/LCD_I2C#1]
I've been trying to get this library to run with a launchpad tm4c123 using the pins for I2c(0) and (1) but can't get anything to display on the LCD using various addresses (0x3F, 0x26, 0x27, 0x28) . I'm using a Sainsmart board with a pcf8574T chip.

**Comment by fmilburn3** [comment]
@raako71 

Thanks for reporting this.  Unfortunately I don't have much familiarity with the TMC123GXL.  There are some threads on 43oh which may be helpful.  For example: http://forum.43oh.com/topic/7147-i2c-on-stellaris-launchpad/

**Comment by raako71** [comment]
you sir are awesome... used this successfully:

```
#include <Wire.h> 
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x3F,16,2);  // set the LCD address to 0x27 for a 16 character, 2 line display

void setup()
{
  Wire.begin(3);
  Wire.setModule(3);

  lcd.init();                      // initialize the lcd 

  // Print a message to the LCD.
  lcd.backlight();
  lcd.print("The world    ");
  lcd.setCursor(0,1); 
  lcd.print("is somewhere");
}

void loop()
{
}
```
